# object = A "bundle" of related attributes and methods(functions)
#         Ex. phone, cup, book
#         You need a "class" to create an object

# class = (blueprint) used to design the structure and layour of an object

# from car import Car

# car1 = Car("Mustang", 2024, "Red", False)
# car2 = Car("Corvette", 2025, "Blue", True)
# car3 = Car("Charger", 2026, "Yellow", True)


# car1.drive()
# print()
# car1.stop()

# car3.describe()   


# print(car1.year)
# print(car1.model)
# print(car1.color)
# print(car1.for_sale)

# print()

# print(car2.year)
# print(car2.model)
# print(car2.color)
# print(car2.for_sale)